[project]
name = "weasyprint-lab"
version = "0.1.0"
description = "Uma pequena demonstração sobre o uso do WeasyPrint junto ao Jinja para rederizar PDFs. Junto a um estudo sobre testes"
readme = "README.md"
authors = [
    { name = "felipesantos2",  email = "santospinheiro627@gmail.com" }
]
requires-python = ">=3.13"

dependencies = [
    "flask>=3.1.3",
    "jinja2>=3.1.6",
    "rich-cli>=1.8.1",
    "weasyprint>=69.0",
]

[project.urls]
Repository =  "https://github.com/felipesantos2/weasyprint_lab"

[project.scripts]
app = "weasyprint_lab.main:app"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-xdist>=3.8.0",
    "ruff>=0.16.3",
    "ty>=0.0.72",
]

[tool.ruff]
line-length=88
fix=true
show-fixes=true

[tool.ty]
